coverage:
  status:
    project:
      default:
        target: 90%    # the required coverage value
        threshold: 66%  # the leniency in hitting the target

comment:
  layout: "reach, diff, flags, files"
  behavior: default