name: SMM

on: [push, pull_request]

jobs:

  test:
    strategy:
      matrix: 
        go: ['1.20']
      
    runs-on: ubuntu-20.04
    name: Go ${{ matrix.go }} Tests

    env:
      TOKEN: ${{ secrets.TOKEN }}
      OWNER: ${{ secrets.OWNER }}
      STAGE: "test"
      NODE: "issue-test"
      EMPTY: "jdf"
      NVMRC_ONLY: "nvmrc_only"
      DJANGO: "virality"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Run tests
      run: go test -v ./...

    - name: Run Coverage
      run: go test -v -cover ./...
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3

